# check-changelog-version: 3
name: Validate Changelog Entry

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0

      - name: Check changelog entry for current version
        run: node .github/scripts/check-changelog.cjs
